### ISSUE TITLE
Hang on standalone application exit

### ISSUE THREAD

**Issue by trandzik** [keijiro/OscJack#23] opened 2020-08-11 16:34 UTC
Hello,
thanks for integrating OSC to Unity, it works great. However I have noticed one issue and thought I might report it here. When using OSC in Editor it works as expected, but I am experiencing hang while trying to exit standalone application. In case I disable Event Receiver (and re-compile) I have no issues with app exit - therefore I assume it is related to OscJack. (Tested on Win10 & Unity 2020.1.1f1)

**Comment by keijiro** [comment] 2020-08-12 05:51
Thanks for reporting it. Could you provide the log file?

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by trandzik** [comment] 2020-08-12 11:05
Sure, but I guess it doesn't contain any useful information.
[Player.log](https://github.com/keijiro/OscJack/files/5062244/Player.log)

**Comment by trandzik** [comment] 2020-08-13 11:06
Hi, I just wanted to let you know (in case it might help you somehow) that I have tried to use OscServer class in order to handle incoming messages and disposing via
```
private void OnApplicationQuit()
{
    server.Dispose();
}
```
results in expected behavior.

**Comment by keijiro** [comment] 2020-11-13 06:13
I can't reproduce this issue on Unity 2020.1.13f1

I'm closing this issue ticket as "not reproducible". Please feel free to reopen it if it still reproduces.

**Closed by keijiro** 2020-11-13 06:13 UTC
Labels: question
